-- Multi-day event support foundation
-- 1) event_days table
-- 2) event_day_id on tickets/bids
-- 3) backfill existing rows
-- 4) auto-resolve event_day_id for new rows

CREATE TABLE IF NOT EXISTS public.event_days (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  day_date DATE NOT NULL,
  label TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT event_days_event_id_day_date_key UNIQUE (event_id, day_date)
);

CREATE INDEX IF NOT EXISTS event_days_event_id_day_date_idx
  ON public.event_days (event_id, day_date);

CREATE INDEX IF NOT EXISTS event_days_day_date_idx
  ON public.event_days (day_date);

ALTER TABLE public.event_days ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'event_days'
      AND policyname = 'Public read event_days'
  ) THEN
    CREATE POLICY "Public read event_days"
      ON public.event_days
      FOR SELECT
      USING (true);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'event_days'
      AND policyname = 'Authenticated insert event_days'
  ) THEN
    CREATE POLICY "Authenticated insert event_days"
      ON public.event_days
      FOR INSERT
      TO authenticated
      WITH CHECK (true);
  END IF;
END
$$;

ALTER TABLE public.tickets
  ADD COLUMN IF NOT EXISTS event_day_id BIGINT;

ALTER TABLE public.bids
  ADD COLUMN IF NOT EXISTS event_day_id BIGINT;

-- One default day for all existing events (auto-single-day migration strategy)
INSERT INTO public.event_days (event_id, day_date)
SELECT
  e.id,
  COALESCE(e.date::date, CURRENT_DATE)
FROM public.events e
ON CONFLICT (event_id, day_date) DO NOTHING;

-- Backfill tickets.event_day_id from their event
UPDATE public.tickets t
SET event_day_id = ed.id
FROM LATERAL (
  SELECT d.id
  FROM public.event_days d
  WHERE d.event_id = t.event_id
  ORDER BY d.day_date ASC
  LIMIT 1
) ed
WHERE t.event_day_id IS NULL
  AND t.event_id IS NOT NULL;

-- Backfill bids.event_day_id from ticket when possible
UPDATE public.bids b
SET event_day_id = t.event_day_id
FROM public.tickets t
WHERE b.event_day_id IS NULL
  AND b.ticket_id = t.id
  AND t.event_day_id IS NOT NULL;

-- Backfill remaining bids.event_day_id from event
UPDATE public.bids b
SET event_day_id = ed.id
FROM LATERAL (
  SELECT d.id
  FROM public.event_days d
  WHERE d.event_id = b.event_id
  ORDER BY d.day_date ASC
  LIMIT 1
) ed
WHERE b.event_day_id IS NULL
  AND b.event_id IS NOT NULL;

ALTER TABLE public.tickets
  DROP CONSTRAINT IF EXISTS tickets_event_day_id_fkey;
ALTER TABLE public.tickets
  ADD CONSTRAINT tickets_event_day_id_fkey
  FOREIGN KEY (event_day_id) REFERENCES public.event_days(id) ON DELETE RESTRICT;

ALTER TABLE public.bids
  DROP CONSTRAINT IF EXISTS bids_event_day_id_fkey;
ALTER TABLE public.bids
  ADD CONSTRAINT bids_event_day_id_fkey
  FOREIGN KEY (event_day_id) REFERENCES public.event_days(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS tickets_event_day_id_idx
  ON public.tickets (event_day_id);

CREATE INDEX IF NOT EXISTS bids_event_day_id_idx
  ON public.bids (event_day_id);

CREATE OR REPLACE FUNCTION public.resolve_ticket_event_day_id()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  resolved_event_day_id BIGINT;
BEGIN
  IF NEW.event_day_id IS NULL AND NEW.event_id IS NOT NULL THEN
    SELECT d.id
      INTO resolved_event_day_id
    FROM public.event_days d
    WHERE d.event_id = NEW.event_id
    ORDER BY d.day_date ASC
    LIMIT 1;

    NEW.event_day_id := resolved_event_day_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tickets_resolve_event_day_id_trg ON public.tickets;
CREATE TRIGGER tickets_resolve_event_day_id_trg
BEFORE INSERT OR UPDATE OF event_id, event_day_id ON public.tickets
FOR EACH ROW
EXECUTE FUNCTION public.resolve_ticket_event_day_id();

CREATE OR REPLACE FUNCTION public.resolve_bid_event_day_id()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  resolved_event_day_id BIGINT;
BEGIN
  IF NEW.event_day_id IS NULL AND NEW.ticket_id IS NOT NULL THEN
    SELECT t.event_day_id
      INTO resolved_event_day_id
    FROM public.tickets t
    WHERE t.id = NEW.ticket_id;

    NEW.event_day_id := resolved_event_day_id;
  END IF;

  IF NEW.event_day_id IS NULL AND NEW.event_id IS NOT NULL THEN
    SELECT d.id
      INTO resolved_event_day_id
    FROM public.event_days d
    WHERE d.event_id = NEW.event_id
    ORDER BY d.day_date ASC
    LIMIT 1;

    NEW.event_day_id := resolved_event_day_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS bids_resolve_event_day_id_trg ON public.bids;
CREATE TRIGGER bids_resolve_event_day_id_trg
BEFORE INSERT OR UPDATE OF event_id, ticket_id, event_day_id ON public.bids
FOR EACH ROW
EXECUTE FUNCTION public.resolve_bid_event_day_id();
